apiVersion: apps/v1
kind: Deployment
metadata:
  name: sketchydraw-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sketchydraw-backend
  template:
    metadata:
      labels:
        app: sketchydraw-backend
    spec:
      serviceAccountName: sa-sketchydraw
      containers:
        - name: backend
          image: 296062560614.dkr.ecr.us-east-1.amazonaws.com/sketchy-backend-app:latest
          ports:
            - containerPort: 5000
          env:
            # CORRECTED: This now loads the full database URI from the correct secret
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: sketchydraw-db-uri # Use the k8s secret created by the CSI driver
                  key: DB_URI
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "sketchydraw-aws-secrets"
