# ...
parameters:
  objects: |
    - objectName: "mongo/user" # <-- CHANGE THIS
      objectType: "secretsmanager"

secretObjects:
- secretName: "sketchydraw-db-uri" 
  type: Opaque
  data:
  - objectName: "mongo/user" # <-- AND CHANGE THIS
    key: "DB_URI"