apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sketchydraw-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "mongodb-manager"
        objectType: "secretsmanager"
  secretObjects:
  - secretName: "sketchydraw-db-uri"
    type: Opaque
    data:
    - key: "DB_URI"
      objectName: "mongodb-manager"