# secretproviderclass-sketchydraw.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sketchydraw-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "sketchydraw/backend" # The name of your secret in AWS Secrets Manager
        objectType: "secretsmanager"

  secretObjects:
  - secretName: "sketchydraw-db-uri" 
    type: Opaque
    data:
    - objectName: "sketchydraw/backend" 
      key: "DB_URI"                   